apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.App_name}}
  labels:
    app: {{ .Values.App_name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.App_name}}
  template:
    metadata:
      labels:
        app: {{ .Values.App_name}}
    spec:
      containers:
        - name: {{ .Values.App_name}}
          image: burlash.azurecr.io/{{ .Values.App_name}}:latest
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: {{ .Values.App_name }}