{{ if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.app_name }}-db
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Values.app_name }}-db
        image: burlash.azurecr.io/{{ .Values.app_name }}-db
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: {{ .Values.app_name }}
{{ end }}